# =====================================================================================
# The following is a necessary configuration for the FixIt theme.
# =====================================================================================

# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "数语轩"
baseURL = "http://fancybit.github.io/"
# Change the default theme to be use when building the site with Hugo
theme = "FixIt"



[markup]
  _merge = "shallow"

[outputs]
  _merge = "shallow"

# -------------------------------------------------------------------------------------
# Taxonomies Configuration
# See: https://gohugo.io/content-management/taxonomies/#configure-taxonomies
# -------------------------------------------------------------------------------------

[taxonomies]
  _merge = "shallow"

# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[params]
  description = "数语轩"  # 网站描述
  languageCode = "zh-CN"          # 语言代码
  enableDarkMode = true           # 启用深色模式

[params.header]
  fixed = true                  # 固定顶部导航栏

[params.footer]
  enable = true                 # 启用页脚

